#version: "3" # Defines the version of Docker Compose file format (version 3 does not support build and link as v2 does but relies on networks)

services:
  nginx:
    depends_on:
     - wordpress
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "8443:443"
    env_file:
      - .env
    networks:
      - inception
    restart: on-failure
    volumes:
     - /home/tstahlhu/data/wordpress:/var/www/html
     #- ./srcs/requirements/nginx/conf/default.conf:/etc/nginx/conf.d

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    networks:
      - inception
    env_file: .env
    restart: unless-stopped
    volumes:
     - /home/tstahlhu/data/mariadb:/var/lib/mysql
    #command: '--default-authentication-plugin=mysql_native_password'

  wordpress:
   container_name: wordpress
   build:
    context: requirements/wordpress
    dockerfile: Dockerfile
   depends_on:
    - mariadb
   ports:
    - "9000:9000"
   networks:
    - inception
   env_file:
    - .env
   restart: unless-stopped
   volumes:
    - /home/tstahlhu/data/wordpress:/var/www/html
    #or should it be var/www/html?
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tstahlhu/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tstahlhu/data/mariadb


networks:
    inception:
     driver: bridge
     external: false