#version: "3" # Defines the version of Docker Compose file format (version 3 does not support build and link as v2 does but relies on networks)

services:
  nginx:
    container_name: nginx
    build:
      context: requirements
      dockerfile: nginx/Dockerfile
    ports:
      - "8443:443"
    env_file:
      - .env
    restart: on-failure

  mariadb:
    container_name: mariadb
    build:
      context: requirements
      dockerfile: mariadb/Dockerfile
    ports:
      - "3306:3306"
    env_file:
      - .env
    restart: unless-stopped
