#version: "3" # Defines the version of Docker Compose file format (version 3 does not support build and link as v2 does but relies on networks)

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    image: nginx-img
    env_file: .env
    networks:
      - inception
    ports:
      - "8443:443"
    restart: on-failure
    volumes:
     - /home/tstahlhu/data/wordpress:/var/www/html/wordpress
     # - wordpress-data:/var/www/html/
     #- ./srcs/requirements/nginx/conf/default.conf:/etc/nginx/conf.d
    depends_on:
      - wordpress

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb-img
    env_file: .env
    networks:
      - inception
    ports:
      - "3306:3306"    
    restart: on-failure #unless-stopped
    volumes:
     - mariadb-data:/var/lib/mysql/
    #command: '--default-authentication-plugin=mysql_native_password'
   # user: "101203:101203"
   # healthcheck:
    #  test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
     # interval: 20s
      #retries: 10
    secrets:
      - credentials
      - db_password
      - db_root_password

  wordpress:
   container_name: wordpress
   build:
    context: requirements/wordpress
    dockerfile: Dockerfile
   image: wp-img
   env_file: .env
   networks:
    - inception
   #ports:
    #- "9000:9000"
   restart: unless-stopped
   depends_on:
     - mariadb
    # mariadb:
     # condition: service_healthy 
   volumes:
    - wordpress-data:/var/www/html/
   #user: "101203:101203"
   secrets:
    - credentials
    - db_password
volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tstahlhu/data/wordpress
  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tstahlhu/data/mariadb


networks:
    inception:
     driver: bridge
    # external: false

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt