#version: "3" # Defines the version of Docker Compose file format (version 3 does not support build and link as v2 does but relies on networks)

services:
  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    env_file:
      - .env
    restart: on-failure
